[build-system]
requires = ["setuptools>=64.0.0", "wheel", "cmake>=3.18"]
build-backend = "setuptools.build_meta"

[project]
name = "pylasr"
version = "0.1.0"
description = "Python bindings for LASR library"
requires-python = ">=3.9" 